"""Sandbox for lambdas generated by the LLM during distillation.

SECURITY MODEL — explicit and documented:

The `safe_compile_lambda` function uses `eval()` deliberately. That is
normally a major risk, so the function gates it behind two strict checks:

  1. Substring blacklist for dunder access (`__`), which is the canonical
     escape vector for restricted Python sandboxes (e.g.,
     `().__class__.__bases__[0].__subclasses__()`).

  2. AST whitelist: the expression must parse as a single ast.Lambda; every
     Call node must target an allowed builtin or an allowed method name;
     every Attribute access must be a whitelisted method; imports,
     assignments, and unusual call targets are rejected.

After both checks pass, the lambda is compiled in an environment where
`__builtins__` is replaced with ONLY the whitelisted builtins. So even if
something slipped through, it cannot reach `open`, `import`, `eval`, etc.

The threat model assumes the LLM (Claude) is cooperative but may produce
buggy or naive Python. We are NOT defending against an adversary who
controls the LLM. For that, a proper subprocess sandbox (RestrictedPython,
firejail, Pyodide) would be required.

We do NOT use ast.literal_eval here because we need to evaluate a callable
(lambda), not a Python literal.
"""
from __future__ import annotations
import ast
import builtins
from typing import Callable

# Substrings that should never appear ANYWHERE in the lambda source.
# We keep this list MINIMAL — the AST check is the real defense. Things
# like "import" or "exec" might legitimately appear inside string literals
# (security_scanner rules need to look for these tokens in the input!), so
# we don't blacklist them at the substring level.
FORBIDDEN_SUBSTRINGS = (
    "__",          # dunder access — main sandbox escape vector
)

# Builtins available inside the lambda
ALLOWED_BUILTINS = {
    "len", "any", "all", "min", "max", "sum",
    "sorted", "set", "list", "dict", "tuple",
    "str", "int", "float", "bool",
    "range", "enumerate", "zip", "reversed",
    "abs", "round",
}

# Method names allowed on str / dict / list etc.
ALLOWED_ATTRS = {
    # str methods
    "lower", "upper", "strip", "lstrip", "rstrip",
    "split", "rsplit", "splitlines", "join",
    "startswith", "endswith", "count", "find", "rfind", "index",
    "replace", "removeprefix", "removesuffix",
    "isdigit", "isalpha", "isalnum", "isspace", "isupper", "islower",
    # dict / list methods we care about
    "get", "keys", "values", "items",
}


class UnsafeLambdaError(ValueError):
    """Raised when a lambda fails sandbox checks."""


def _check_substrings(lambda_str: str) -> None:
    """Layer 1: reject dunder access and nested lambdas."""
    for forbidden in FORBIDDEN_SUBSTRINGS:
        if forbidden in lambda_str:
            raise UnsafeLambdaError(f"forbidden token: {forbidden!r}")
    # Allow exactly ONE `lambda` keyword — at the start
    if lambda_str.lstrip().count("lambda") != 1:
        raise UnsafeLambdaError("expected exactly one 'lambda' keyword")


def _check_ast(lambda_str: str) -> None:
    """Layer 2: parse + walk AST, reject disallowed constructs."""
    try:
        tree = ast.parse(lambda_str, mode="eval")
    except SyntaxError as e:
        raise UnsafeLambdaError(f"syntax error: {e}")

    if not isinstance(tree.body, ast.Lambda):
        raise UnsafeLambdaError("expression is not a lambda")

    for node in ast.walk(tree):
        # No imports of any kind
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            raise UnsafeLambdaError("import forbidden")

        # Attribute access: must be a whitelisted method name; no dunders
        if isinstance(node, ast.Attribute):
            if node.attr.startswith("_"):
                raise UnsafeLambdaError(f"private attribute: {node.attr}")
            if node.attr not in ALLOWED_ATTRS:
                raise UnsafeLambdaError(f"attribute not whitelisted: {node.attr}")

        # Function calls: target must be a whitelisted builtin name or a
        # method call (attribute call). Anything else is suspicious.
        if isinstance(node, ast.Call):
            if isinstance(node.func, ast.Name):
                if node.func.id not in ALLOWED_BUILTINS:
                    raise UnsafeLambdaError(f"builtin not allowed: {node.func.id}")
            elif isinstance(node.func, ast.Attribute):
                pass  # method call — attribute already validated above
            else:
                raise UnsafeLambdaError(
                    f"unusual call target: {type(node.func).__name__}"
                )

        # No assignments (walrus, etc.)
        if isinstance(node, (ast.NamedExpr, ast.Assign, ast.AugAssign)):
            raise UnsafeLambdaError("assignment forbidden inside lambda")


def safe_compile_lambda(lambda_str: str) -> Callable[[str, dict], bool]:
    """Compile an LLM-generated lambda string after sandbox checks.

    See module docstring for the security model. The eval() here is
    intentional and gated by `_check_substrings` and `_check_ast` above.

    Returns the callable on success. Raises UnsafeLambdaError on rejection.
    The returned callable takes (signal: str, context: dict) and returns bool.
    """
    lambda_str = lambda_str.strip()
    _check_substrings(lambda_str)
    _check_ast(lambda_str)

    # Compile in a restricted namespace where __builtins__ is replaced with
    # only the whitelisted builtin functions. This is defense-in-depth — the
    # AST check above already rejected calls to anything not whitelisted.
    safe_builtins = {name: getattr(builtins, name) for name in ALLOWED_BUILTINS}
    safe_globals: dict[str, object] = {"__builtins__": safe_builtins}
    try:
        # eval() is intentional here: the input has passed two strict checks
        # and runs with a restricted builtins dict. See module docstring.
        fn = eval(lambda_str, safe_globals, {})  # noqa: S307
    except Exception as e:
        raise UnsafeLambdaError(f"compile failed: {e}")
    if not callable(fn):
        raise UnsafeLambdaError("did not compile to a callable")
    return fn
